/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SellerListingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const SellerListing = IDL.Record({
  'id' : IDL.Nat,
  'status' : SellerListingStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'shippingInfo' : IDL.Text,
  'contactEmail' : IDL.Text,
  'category' : IDL.Text,
  'commissionRate' : IDL.Float64,
  'sellerId' : IDL.Principal,
  'contactWhatsApp' : IDL.Text,
  'price' : IDL.Float64,
});
export const SellerProfile = IDL.Record({
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
  'storeName' : IDL.Text,
  'contactEmail' : IDL.Text,
  'sellerId' : IDL.Principal,
  'contactWhatsApp' : IDL.Text,
});
export const Brand = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'logoUrl' : IDL.Text,
  'category' : IDL.Text,
  'affiliateLink' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'vendor' : IDL.Text,
  'dealOfDay' : IDL.Bool,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Float64,
});
export const SocialLinks = IDL.Record({
  'twitter' : IDL.Text,
  'instagram' : IDL.Text,
  'threads' : IDL.Text,
  'whatsapp' : IDL.Text,
  'facebook' : IDL.Text,
  'telegram' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBrand' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBrand' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSellerListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAffiliateCode' : IDL.Func([], [IDL.Text], ['query']),
  'getAllSellerListingsAdmin' : IDL.Func(
      [],
      [IDL.Vec(SellerListing)],
      ['query'],
    ),
  'getAllSellerProfiles' : IDL.Func([], [IDL.Vec(SellerProfile)], ['query']),
  'getBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDealOfDay' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMySellerListings' : IDL.Func([], [IDL.Vec(SellerListing)], ['query']),
  'getMySellerProfile' : IDL.Func([], [IDL.Opt(SellerProfile)], ['query']),
  'getPendingSellerListings' : IDL.Func(
      [],
      [IDL.Vec(SellerListing)],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getSellerListingById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SellerListing)],
      ['query'],
    ),
  'getSellerListings' : IDL.Func([], [IDL.Vec(SellerListing)], ['query']),
  'getSellerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SellerProfile)],
      ['query'],
    ),
  'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerSellerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAffiliateCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setDealOfDay' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'setFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'submitSellerListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateSellerListingStatus' : IDL.Func(
      [IDL.Nat, SellerListingStatus],
      [IDL.Bool],
      [],
    ),
  'updateSocialLinks' : IDL.Func([SocialLinks], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SellerListingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const SellerListing = IDL.Record({
    'id' : IDL.Nat,
    'status' : SellerListingStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'shippingInfo' : IDL.Text,
    'contactEmail' : IDL.Text,
    'category' : IDL.Text,
    'commissionRate' : IDL.Float64,
    'sellerId' : IDL.Principal,
    'contactWhatsApp' : IDL.Text,
    'price' : IDL.Float64,
  });
  const SellerProfile = IDL.Record({
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
    'storeName' : IDL.Text,
    'contactEmail' : IDL.Text,
    'sellerId' : IDL.Principal,
    'contactWhatsApp' : IDL.Text,
  });
  const Brand = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'logoUrl' : IDL.Text,
    'category' : IDL.Text,
    'affiliateLink' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'vendor' : IDL.Text,
    'dealOfDay' : IDL.Bool,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Float64,
  });
  const SocialLinks = IDL.Record({
    'twitter' : IDL.Text,
    'instagram' : IDL.Text,
    'threads' : IDL.Text,
    'whatsapp' : IDL.Text,
    'facebook' : IDL.Text,
    'telegram' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBrand' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBrand' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSellerListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAffiliateCode' : IDL.Func([], [IDL.Text], ['query']),
    'getAllSellerListingsAdmin' : IDL.Func(
        [],
        [IDL.Vec(SellerListing)],
        ['query'],
      ),
    'getAllSellerProfiles' : IDL.Func([], [IDL.Vec(SellerProfile)], ['query']),
    'getBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDealOfDay' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMySellerListings' : IDL.Func([], [IDL.Vec(SellerListing)], ['query']),
    'getMySellerProfile' : IDL.Func([], [IDL.Opt(SellerProfile)], ['query']),
    'getPendingSellerListings' : IDL.Func(
        [],
        [IDL.Vec(SellerListing)],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSellerListingById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SellerListing)],
        ['query'],
      ),
    'getSellerListings' : IDL.Func([], [IDL.Vec(SellerListing)], ['query']),
    'getSellerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SellerProfile)],
        ['query'],
      ),
    'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerSellerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAffiliateCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setDealOfDay' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'setFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'submitSellerListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateSellerListingStatus' : IDL.Func(
        [IDL.Nat, SellerListingStatus],
        [IDL.Bool],
        [],
      ),
    'updateSocialLinks' : IDL.Func([SocialLinks], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };