/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Brand {
  'id' : bigint,
  'name' : string,
  'logoUrl' : string,
  'category' : string,
  'affiliateLink' : string,
}
export interface Product {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'vendor' : string,
  'dealOfDay' : boolean,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'affiliateLink' : string,
  'price' : number,
}
export interface SocialLinks {
  'twitter' : string,
  'instagram' : string,
  'threads' : string,
  'whatsapp' : string,
  'facebook' : string,
  'telegram' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBrand' : ActorMethod<[string, string, string, string], bigint>,
  'addProduct' : ActorMethod<
    [string, string, string, number, string, string, number, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBrand' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getBrands' : ActorMethod<[], Array<Brand>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDealOfDay' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getSocialLinks' : ActorMethod<[], SocialLinks>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDealOfDay' : ActorMethod<[bigint, boolean], boolean>,
  'setFeatured' : ActorMethod<[bigint, boolean], boolean>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      number,
      string,
      string,
      number,
      string,
      string,
    ],
    boolean
  >,
  'updateSocialLinks' : ActorMethod<[SocialLinks], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];