/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Brand {
  'id' : bigint,
  'name' : string,
  'logoUrl' : string,
  'category' : string,
  'affiliateLink' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'productTitle' : string,
  'customerPhone' : string,
  'sellerListingId' : [] | [bigint],
  'createdAt' : bigint,
  'sellingPrice' : number,
  'productId' : bigint,
  'orderType' : OrderType,
  'updatedAt' : bigint,
  'customerAddress' : string,
  'quantity' : bigint,
  'customerId' : Principal,
  'customerEmail' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'forwarded' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export type OrderType = { 'marketplace' : null } |
  { 'affiliate' : null };
export interface Product {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'vendor' : string,
  'dealOfDay' : boolean,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'affiliateLink' : string,
  'price' : number,
}
export interface SellerListing {
  'id' : bigint,
  'status' : SellerListingStatus,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'shippingInfo' : string,
  'contactEmail' : string,
  'category' : string,
  'commissionRate' : number,
  'sellerId' : Principal,
  'contactWhatsApp' : string,
  'price' : number,
}
export type SellerListingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SellerProfile {
  'createdAt' : bigint,
  'description' : string,
  'logoUrl' : string,
  'storeName' : string,
  'contactEmail' : string,
  'sellerId' : Principal,
  'contactWhatsApp' : string,
}
export interface SocialLinks {
  'twitter' : string,
  'instagram' : string,
  'threads' : string,
  'whatsapp' : string,
  'facebook' : string,
  'telegram' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBrand' : ActorMethod<[string, string, string, string], bigint>,
  'addProduct' : ActorMethod<
    [string, string, string, number, string, string, number, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBrand' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteSellerListing' : ActorMethod<[bigint], boolean>,
  'getAffiliateCode' : ActorMethod<[], string>,
  'getAllOrdersAdmin' : ActorMethod<[], Array<Order>>,
  'getAllSellerListingsAdmin' : ActorMethod<[], Array<SellerListing>>,
  'getAllSellerProfiles' : ActorMethod<[], Array<SellerProfile>>,
  'getBrands' : ActorMethod<[], Array<Brand>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDealOfDay' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMySellerListings' : ActorMethod<[], Array<SellerListing>>,
  'getMySellerProfile' : ActorMethod<[], [] | [SellerProfile]>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getPendingSellerListings' : ActorMethod<[], Array<SellerListing>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getSellerListingById' : ActorMethod<[bigint], [] | [SellerListing]>,
  'getSellerListings' : ActorMethod<[], Array<SellerListing>>,
  'getSellerProfile' : ActorMethod<[Principal], [] | [SellerProfile]>,
  'getSocialLinks' : ActorMethod<[], SocialLinks>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      OrderType,
      [] | [bigint],
      bigint,
      number,
    ],
    bigint
  >,
  'registerSellerProfile' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAffiliateCode' : ActorMethod<[string], boolean>,
  'setDealOfDay' : ActorMethod<[bigint, boolean], boolean>,
  'setFeatured' : ActorMethod<[bigint, boolean], boolean>,
  'submitSellerListing' : ActorMethod<
    [string, string, string, number, string, string, string, string],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      number,
      string,
      string,
      number,
      string,
      string,
    ],
    boolean
  >,
  'updateSellerListingStatus' : ActorMethod<
    [bigint, SellerListingStatus],
    boolean
  >,
  'updateSocialLinks' : ActorMethod<[SocialLinks], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];